-- seed :: expanded processing methods -> ref_processes
-- Adds the modern fermentation/experimental + decaf + regional methods the base
-- seed omits. explainer = "what actually happens"; flavor_effect = cup signature.
-- INSERT OR IGNORE — never clobbers the 12 base processes.


INSERT OR IGNORE INTO ref_processes (id,name,category,explainer,flavor_effect,aliases,updated_at) VALUES
 ('washed-anaerobic','Anaerobic Washed','experimental',
  'Depulped beans ferment in sealed, oxygen-free tanks before being washed and dried. Controlled microbes build aromatics while keeping washed-style clarity.',
  'Clean but amplified — bright, vivid, often floral or candied','["anaerobic fermentation (washed)"]','2026-06-03'),
 ('double-fermentation','Double Fermentation','experimental',
  'Two distinct fermentation stages (e.g. a sealed anaerobic phase, then a second ferment in or out of water) before drying, each shaping the microbial profile.',
  'Layered, intense, deep fruit and ferment complexity','["double ferment"]','2026-06-03'),
 ('extended-fermentation','Extended Fermentation','experimental',
  'Fermentation is deliberately prolonged (often many tens of hours, frequently sealed) to push aromatic development further than a conventional ferment.',
  'Bold, funky, wine-like, high intensity','["long fermentation"]','2026-06-03'),
 ('lactic','Lactic','experimental',
  'Low-oxygen fermentation steered toward lactic-acid bacteria (controlled temperature, limited airflow), favoring lactic over acetic pathways.',
  'Creamy, dense, yogurt/dairy sweetness, soft acidity','["lactic fermentation"]','2026-06-03'),
 ('thermal-shock','Thermal Shock','experimental',
  'After fermentation the coffee is rinsed through alternating hot and cold water baths; the sudden temperature swing is used to fix and shape aromatics.',
  'Vivid, clean, intense fruit clarity','["shock thermal","thermal shock washed"]','2026-06-03'),
 ('koji','Koji','experimental',
  'Cherries or beans are inoculated with Aspergillus oryzae (koji), the mold used for miso/sake, which breaks down sugars and proteins during fermentation.',
  'Umami, savory-sweet, deep complexity','["koji fermentation"]','2026-06-03'),
 ('yeast-inoculated','Yeast Inoculated','experimental',
  'Selected cultured yeast strains are added at fermentation to steer the microbial community toward a target flavor outcome rather than relying on wild flora.',
  'Targeted, consistent fruit/floral expression','["cultured yeast","inoculated fermentation"]','2026-06-03'),
 ('carbonic-natural','Carbonic Natural','experimental',
  'Whole cherries ferment under a CO2 blanket (carbonic maceration) and are then dried intact as a natural.',
  'Explosive clean fruit, syrupy, distinctive aromatics','["natural carbonic maceration"]','2026-06-03'),
 ('mosto','Mosto','experimental',
  'Beans are fermented submerged in concentrated mucilage juice (mosto/mossto) collected from depulping, intensifying sugar-driven fermentation.',
  'Intense sweetness, syrupy fruit','["mossto","mucilage juice"]','2026-06-03'),
 ('co-fermented','Co-Fermented / Infused','experimental',
  'Fruit, spices, or other flavorings are added to the fermentation. Controversial — flavor can come from the additive rather than terroir; disclosure matters.',
  'Overt added-flavor notes (e.g. cinnamon, berry, tropical)','["infused","flavored fermentation"]','2026-06-03'),
 ('kenya-washed','Kenya Washed (72-hour)','washed',
  'The classic Kenyan double-wash: ferment, wash, a second soak under clean water for up to ~72 hours total, then dry. The long clean soak sharpens acidity.',
  'Extremely clean, juicy, blackcurrant, vivid acidity','["double washed","Kenya double fermentation"]','2026-06-03'),
 ('pulped-natural','Pulped Natural','honey',
  'Brazilian method: skin removed, then dried with most mucilage still on the bean. The bridge between washed and natural that the honey styles refined.',
  'Sweet, rounded, medium body, mild acidity','["semi-washed (Brazil)"]','2026-06-03'),
 ('monsooned','Monsooned','natural',
  'Indian method: dried green beans are exposed to humid monsoon winds for weeks, swelling and mellowing them (originally mimicking long sea voyages).',
  'Very low acidity, heavy body, musty/spicy, woody','["monsooned malabar"]','2026-06-03'),
 ('decaf-ea','Decaf — Sugarcane (EA)','decaf',
  'Beans are decaffeinated with ethyl acetate derived from fermented sugarcane, which selectively bonds to and removes caffeine.',
  'Retains sweetness and body; common for Latin American decaf','["ethyl acetate","natural decaf","sugarcane decaf"]','2026-06-03'),
 ('decaf-co2','Decaf — CO2','decaf',
  'Supercritical CO2 under pressure strips caffeine from moistened green beans while leaving most flavor compounds behind.',
  'Clean, flavor-preserving decaffeination','["supercritical CO2","mountain water (CO2)"]','2026-06-03');
