-- AUTO-GENERATED from the official WCR catalog PDF (147pp, complete-1769602232.pdf)
-- Source: World Coffee Research Arabica + Robusta Variety Catalogs.
-- 83 new varieties INSERTed + 16 prior memory-written rows CORRECTED to source.
-- Fields parsed directly from catalog: genetic description (->lineage), bean size, yield,
-- quality-at-altitude (->flavor_potential), optimal-altitude category (->masl range), leaf-rust.
-- Curated/derived fact rows w/ per-variety source_url; NOT verbatim redistribution. CC BY-NC-ND.

INSERT OR IGNORE INTO ref_varieties
 (id,name,species,lineage,optimal_alt_min_m,optimal_alt_max_m,yield_potential,rust_resistance,bean_size,flavor_potential,notes,source,source_url,updated_at) VALUES
 ('ab3','AB3','arabica','Ethiopian landrace',1300,2000,'medium','tolerant','large','Good cup quality potential at high altitude.','High cup quality, adapted for agroforestry; limited cultivation in Java','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/ab3','2026-06-03'),
 ('bourbon-mayaguez-139','Bourbon Mayaguez 139','arabica','Bourbon-Typica group (Bourbon related)',1300,2000,'medium','susceptible','large','Very Good cup quality potential at high altitude.','Vigorous and highly productive tall variety with very good cup quality. Found commonly in Rwanda and Burundi.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bourbon-mayaguez-139','2026-06-03'),
 ('bourbon-mayaguez-71','Bourbon Mayaguez 71','arabica','Bourbon-Typica group (Bourbon related)',1000,2000,'medium','susceptible','large','Good cup quality potential at high altitude.','Moderate yield, good cup potential, and susceptible to major diseases. Adapted for medium altitudes. Found commonly in Rwanda and Burundi.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bourbon-mayaguez-71','2026-06-03'),
 ('bpl10','BPL10','arabica','Bourbon-Typica group (Typica related)',1300,2000,'medium','resistant','large','Very Good cup quality potential at high altitude.','Rust-tolerant with high vigor; limited cultivation in Java.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bpl10','2026-06-03'),
 ('caripe','Caripe','arabica','Bourbon-Typica group (Typica related)',1000,2000,'medium','susceptible','large','Very Good cup quality potential at high altitude.','Very good cup quality with large beans. An important regional variety in Monagas state in northeastern Venezuela.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/caripe','2026-06-03'),
 ('casiopea','Casiopea','arabica','F1 hybrid (not introgressed)',1300,2000,'high','susceptible','large','Exceptional cup quality potential at high altitude.','High yielding variety, with exceptional quality at elevations above 1300 meters.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/casiopea','2026-06-03'),
 ('catimor-129','Catimor 129','arabica','Introgressed (Catimor related)',1300,2000,'high','tolerant','large','Good cup quality potential at high altitude.','High yielding/Dwarf/Compact variety resistant to coffee leaf rust and coffee berry disease. Found commonly in Malawi, Zambia, and Zimbabwe.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/catimor-129','2026-06-03'),
 ('catisic','Catisic','arabica','Introgressed (Catimor related)',500,1400,'high','tolerant','medium','Very Low cup quality potential at high altitude.','Adapted to warmest zones and acidic soils. High yielding.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/catisic','2026-06-03'),
 ('cuscatleco','Cuscatleco','arabica','Introgressed (Sarchimor related)',500,1400,'medium','tolerant','large','Good cup quality potential at high altitude.','Well-adapted to medium altitudes. Resistant to coffee leaf rust and some nematodes.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/cuscatleco','2026-06-03'),
 ('ec15','EC15','arabica','F1 hybrid (not introgressed)',1000,2000,'high','susceptible','large','Very Good cup quality potential at high altitude.','High production yield and very good quality potential. Suitable for agroforestry systems.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/ec15','2026-06-03'),
 ('esperanza','Esperanza','arabica','F1 hybrid (introgressed)',500,2000,'high','resistant','large','Very Good cup quality potential at high altitude.','Variety with very high productivity, tolerance to rust, and very good quality. Excellent adaptation to humid environments.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/esperanza','2026-06-03'),
 ('evaluna','Evaluna','arabica','F1 hybrid (introgressed)',1300,2000,'high','tolerant','large','Very Good cup quality potential at high altitude.','Very high yielding variety at elevations at high altitudes.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/evaluna','2026-06-03'),
 ('fronton','Fronton','arabica','Introgressed (Catimor related)',500,1400,'medium','tolerant','medium','Good cup quality potential at high altitude.','Early production and high yielding plant resistant to coffee leaf rust. Well- adapted to low and medium altitudes. Found primarily in Puerto Rico.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/fronton','2026-06-03'),
 ('h3','H3','arabica','F1 hybrid (not introgressed)',1300,2000,'high','susceptible','large','Very Good cup quality potential at high altitude.','High yielding variety, with very good quality at elevations above 1300 meters.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/h3','2026-06-03'),
 ('harar-rwanda','Harar Rwanda','arabica','Bourbon-Typica group (Typica related)',1000,2000,'high','susceptible','medium','Very Good cup quality potential at high altitude.','High yielding with very good cup quality potential, but susceptible to the major diseases and prone to die back. This is the Harar variety sometimes found in Rwanda (no longer recommended by Rwandan coffee authorities because of its short productive life)','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/harar-rwanda','2026-06-03'),
 ('ihcafe-90','IHCAFE 90','arabica','Introgressed (Catimor related)',500,1400,'high','susceptible','medium','Very Low cup quality potential at high altitude.','High yielding plant adapted to lowest altitudes. Requires high fertilization.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/ihcafe-90','2026-06-03'),
 ('ipr-103','IPR 103','arabica','Introgressed (Sarchimor related)',1000,1400,'high','resistant','medium','Very Good cup quality potential at high altitude.','Good tolerance to heat, drought, and low-fertility soil. Adapted to various coffee-growing regions in Brazil, with high productivity especially in the early harvests.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/ipr-103','2026-06-03'),
 ('ipr-107','IPR 107','arabica','Introgressed (Sarchimor related)',1000,2000,'high','resistant','large','Very Good cup quality potential at high altitude.','Highly resistant to coffee leaf rust, suitable for high altitude cultivation and mechanical harvesting.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/ipr-107','2026-06-03'),
 ('kartika-1','Kartika 1','arabica','Introgressed (Catimor related)',1300,2000,'medium','resistant','medium','Good cup quality potential at high altitude.','Adapted for agroforestry, with good yields and high resistance to rust in global trials.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kartika-1','2026-06-03'),
 ('kp423','KP423','arabica','Bourbon-Typica group (Bourbon related)',1000,1400,'high','tolerant','medium','Low cup quality potential at high altitude.','Tolerant of drought and coffee leaf rust but highly susceptible to coffee berry disease. Found mostly in Uganda.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kp423','2026-06-03'),
 ('lempira','Lempira','arabica','Introgressed (Catimor related)',500,1400,'high','tolerant','medium','Low cup quality potential at high altitude.','High yielding variety adapted to warmest zones and acidic soils.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/lempira','2026-06-03'),
 ('monte-claro','Monte Claro','arabica','Introgressed (Sarchimor related)',1000,1400,'high','tolerant','very large','Very Good cup quality potential at high altitude.','Compact variety with very good cup quality and large beans, tolerance to coffee leaf rust and nematodes, and high yield potential. An important regional variety in Venezuela.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/monte-claro','2026-06-03'),
 ('mundo-maya','Mundo Maya','arabica','F1 hybrid (introgressed)',1000,2000,'high','resistant','large','Very Good cup quality potential at high altitude.','Very high yielding variety if planted in healthy soil, with very good quality at elevations above 1300 meters. Well-adapted to agroforestery conditions.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/mundo-maya','2026-06-03'),
 ('nayarita','Nayarita','arabica','F1 hybrid (introgressed)',1300,2000,'high','susceptible','large','Very Good cup quality potential at high altitude.','High yielding variety at high altitudes with very good cup quality.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/nayarita','2026-06-03'),
 ('nyasaland','Nyasaland','arabica','Bourbon-Typica group (Typica related)',1000,2000,'medium','susceptible','medium','Good cup quality potential at high altitude.','Good cup quality, but susceptible to major diseases. Preferred by smallholder farmers in Uganda.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/nyasaland','2026-06-03'),
 ('oro-azteca','Oro Azteca','arabica','Introgressed (Catimor related)',500,1400,'high','tolerant','medium','Good cup quality potential at high altitude.','Adapted to warmest zones and acidic soils. High yielding.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/oro-azteca','2026-06-03'),
 ('paraiso','Paraiso','arabica','Introgressed (Sarchimor related)',1000,1400,'medium','tolerant','large','Good cup quality potential at high altitude.','Very high-yielding and rust-resistant compact variety developed in Brazil and recently introduced to Central America.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/paraiso','2026-06-03'),
 ('pop3303','Pop3303/21','arabica','Bourbon-Typica group (Typica related)',1000,2000,'high','tolerant','medium','Good cup quality potential at high altitude.','High yielding with tolerance to drought, coffee leaf rust, and coffee berry disease. Adapted to a wide range of ecosystems. Found mostly in Rwanda.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/pop3303','2026-06-03'),
 ('rab-c15','RAB C15','arabica','Introgressed (Other)',1000,2000,'high','tolerant','large','Very Good cup quality potential at high altitude.','High yielding tall variety resistant to rust and coffee berry disease recently released in Rwanda.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/rab-c15','2026-06-03'),
 ('s4808','S4808','arabica','Introgressed (Other)',500,1400,'high','resistant','large','Good cup quality potential at high altitude.','An Indian breeding line this is not yet commercially released.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/s4808','2026-06-03'),
 ('s795','S795','arabica','Introgressed (Other)',1000,2000,'high','susceptible','large','Very Good cup quality potential at high altitude.','High-yielding variety that is widely cultivated in India.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/s795','2026-06-03'),
 ('sln-5b','Sln.5B','arabica','Introgressed (Other)',1300,2000,'high','resistant','large','Good cup quality potential at high altitude.','High yield and strong rust tolerance coming from both robusta and liberica parentage.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sln-5b','2026-06-03'),
 ('sln-6','Sln.6','arabica','Introgressed (Other)',1000,1400,'medium','resistant','large','Good cup quality potential at high altitude.','Adapted to mid-to-high altitude Indian tropics, with good rust resistance and yields.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sln-6','2026-06-03'),
 ('t5175','T5175','arabica','Introgressed (Catimor related)',500,1400,'high','tolerant','medium','Very Low cup quality potential at high altitude.','High-yielding plant adapted to lowest altitudes. Requires high fertilization. Variety not uniform.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/t5175','2026-06-03'),
 ('t8667','T8667','arabica','Introgressed (Catimor related)',500,1400,'high','tolerant','medium','Low cup quality potential at high altitude.','High-yielding variety, resistant to rust, and adapted to warmest zones and acidic soils.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/t8667','2026-06-03'),
 ('venecia','Venecia','arabica','Bourbon-Typica group (Bourbon related)',1000,2000,'medium','susceptible','large','Good cup quality potential at high altitude.','Very high susceptibility to coffee leaf rust. Well-adapted to rainy zones due to late harvest during dry season.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/venecia','2026-06-03'),
 ('bp-534','BP 534','robusta','Congo group',NULL,NULL,'low','resistant','large',NULL,'Most commonly grown clone by farmers in Indonesia; suitable for cultivation under agroforestry systems. Yield ~1700-2200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bp-534','2026-06-03'),
 ('bp-936','BP 936','robusta','Congo group',NULL,NULL,'low','resistant','large',NULL,'Wide adaptability to different environments, with optimal productivity in areas with wet climates; suitable for cultivation under agroforestry systems. Yield ~1600-2200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bp-936','2026-06-03'),
 ('bp-939','BP 939','robusta','Congo group',NULL,NULL,'low','resistant','large',NULL,'Wide adaptability to different environments that produces best in areas with dry climates; suitable for cultivation under agroforestry systems. Yield ~1400-1900 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/bp-939','2026-06-03'),
 ('brs-1216','BRS 1216','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Adaptable to the environments of the Western Amazon with high productivity. Plant structure suitable for mechanized harvesting. Resistant to nematodes and coffee rust. Yield ~7200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-1216','2026-06-03'),
 ('brs-2299','BRS 2299','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Plant structure suitable for mechanized harvesting. Stands out for its tolerance to the root-knot nematode Meloidogyne sp. Yield ~6600 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-2299','2026-06-03'),
 ('brs-2314','BRS 2314','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','small',NULL,'High cupping scores; has been classified as a ''fine robusta.'' Yield ~6600 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-2314','2026-06-03'),
 ('brs-2336','BRS 2336','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Adaptable to the environments of the Western Amazon, with high productivity and bean size. Yield ~7200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-2336','2026-06-03'),
 ('brs-2357','BRS 2357','robusta','Guinea x Congo group',NULL,NULL,'high','susceptible','medium',NULL,'Compact canopy, which allows for densification. Short stems allow one additional harvest before renewal. Yield ~6000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-2357','2026-06-03'),
 ('brs-3137','BRS 3137','robusta','Guinea x Congo group',NULL,NULL,'high','tolerant','small',NULL,'Recognized for its rusticity, presenting good vegetative and productive characteristics in dry conditions and low-fertility soils. Yield ~6600 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-3137','2026-06-03'),
 ('brs-3193','BRS 3193','robusta','Guinea x Congo group',NULL,NULL,'high','tolerant','small',NULL,'Long primary branches. Production peak in the second or third commercial harvest due to its initial growth, which reduces the biannual production of the crop by compensating for lower yields of other clones. Yield ~6000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-3193','2026-06-03'),
 ('brs-3210','BRS 3210','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Good adaptability and stability in the environments of the Western Amazon. Good productivity and bean size. Yield ~7200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-3210','2026-06-03'),
 ('brs-3213','BRS 3213','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Adaptable to the environments of the Western Amazon recognized for good productivity and bean size. Yield ~7200 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-3213','2026-06-03'),
 ('brs-3220','BRS 3220','robusta','Guinea x Congo group',NULL,NULL,'high','resistant','medium',NULL,'Adaptable to the environments of the Western Amazon, recognized for good productivity and bean size. Yield ~6600 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/brs-3220','2026-06-03'),
 ('inifap-00-24','INIFAP 00-24','robusta','Guinea group',NULL,NULL,NULL,'tolerant','medium',NULL,'Compact plant grown under the conditions of the Chiapas coast in Mexico. Reduced plant size lends itself to higher yields in dry conditions and differentiates it from any other clone.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/inifap-00-24','2026-06-03'),
 ('inifap-00-28','INIFAP 00-28','robusta','Congo group',NULL,NULL,NULL,'tolerant','medium',NULL,'Tall plants with large and numerous leaves and fruits; highest-yielding clone for the conditions of the coast of Chiapas, Mexico.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/inifap-00-28','2026-06-03'),
 ('inifap-95-9','INIFAP 95-9','robusta','Congo group',NULL,NULL,NULL,'tolerant','large',NULL,'Tall plant with very large fruit. Susceptible to shoot hole borer.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/inifap-95-9','2026-06-03'),
 ('inifap-97-14','INIFAP 97-14','robusta','Congo group',NULL,NULL,NULL,'tolerant','medium',NULL,'Tall growth, tendency to form plants with more than three productive stems and good yield of cherries. Very susceptible to stem borers and anthracnose.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/inifap-97-14','2026-06-03'),
 ('inifap-97-15','INIFAP 97-15','robusta','Guinea group',NULL,NULL,NULL,NULL,'medium',NULL,'Tall growth, tendency to form plants with more than three productive stems. Good yield potential, wide range of adaptation to the climatic conditions of the coast of Chiapas and Veracruz, Mexico.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/inifap-97-15','2026-06-03'),
 ('kr-1','NARO-Kituza Robusta 1','robusta','Uganda group',NULL,NULL,'medium','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~2800 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-1','2026-06-03'),
 ('kr-10','NARO-Kituza Robusta 10','robusta','Uganda group',NULL,NULL,'high','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~4800 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-10','2026-06-03'),
 ('kr-2','NARO-Kituza Robusta 2','robusta','Uganda group',NULL,NULL,'medium','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~2600 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-2','2026-06-03'),
 ('kr-3','NARO-Kituza Robusta 3','robusta','Uganda group',NULL,NULL,'high','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~4900 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-3','2026-06-03'),
 ('kr-4','NARO-Kituza Robusta 4','robusta','Uganda group',NULL,NULL,'low','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~2300 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-4','2026-06-03'),
 ('kr-5','NARO-Kituza Robusta 5','robusta','Uganda group',NULL,NULL,'medium','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~2860 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-5','2026-06-03'),
 ('kr-6','NARO-Kituza Robusta 6','robusta','Uganda group',NULL,NULL,'medium','resistant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~2650 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-6','2026-06-03'),
 ('kr-7','NARO-Kituza Robusta 7','robusta','Uganda group',NULL,NULL,'medium','tolerant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~3000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-7','2026-06-03'),
 ('kr-8','NARO-Kituza Robusta 8','robusta','Uganda group',NULL,NULL,'medium','tolerant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~3100 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-8','2026-06-03'),
 ('kr-9','NARO-Kituza Robusta 9','robusta','Uganda group',NULL,NULL,'medium','tolerant','medium',NULL,'Resistant to coffee wilt disease (CWD). Yield ~3900 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/kr-9','2026-06-03'),
 ('perdenia','Perdenia','robusta','Congo group',NULL,NULL,'medium','tolerant','small',NULL,'Vigorous, wide-spreading, grow into moderately large trees. High-yielding, beans relatively small in size. Yield ~1500-3000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/perdenia','2026-06-03'),
 ('roubi-1','Roubi 1','robusta',NULL,NULL,NULL,'high','resistant','medium',NULL,'Combines excellent yield and cup quality. Very high acceptance among farmers.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-1','2026-06-03'),
 ('roubi-10','Roubi 10','robusta',NULL,NULL,NULL,'high','resistant','medium',NULL,'High productivity and high cup quality.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-10','2026-06-03'),
 ('roubi-2','Roubi 2','robusta',NULL,NULL,NULL,'high','resistant','large',NULL,'Combines excellent yield and cup quality. Very high acceptance among farmers.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-2','2026-06-03'),
 ('roubi-4','Roubi 4','robusta',NULL,NULL,NULL,'high','resistant','large',NULL,'High productivity in combination with large bean size.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-4','2026-06-03'),
 ('roubi-5','Roubi 5','robusta',NULL,NULL,NULL,'high','resistant','large',NULL,'High produtivity in combination with large bean size.','World Coffee Research',NULL,'2026-06-03'),
 ('roubi-6','Roubi 6','robusta',NULL,NULL,NULL,'high','resistant','medium',NULL,'High productivity and high cup quality.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-6','2026-06-03'),
 ('roubi-7','Roubi 7','robusta',NULL,NULL,NULL,'high','resistant','small',NULL,'Very good cup quality and high productivity.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-7','2026-06-03'),
 ('roubi-8','Roubi 8','robusta',NULL,NULL,NULL,'high','resistant','medium',NULL,'High productivity and high cup quality.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-8','2026-06-03'),
 ('roubi-9','Roubi 9','robusta',NULL,NULL,NULL,'high','resistant','small',NULL,'High productivity and high cup quality.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/roubi-9','2026-06-03'),
 ('sa-237','SA 237','robusta','Congo group',NULL,NULL,'low','resistant','large',NULL,'Suitable for cultivation under agroforestry systems in areas with dry climates. Yield ~800-2100 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sa-237','2026-06-03'),
 ('sln-1-r','Sln.1R','robusta','Guinea x Coffea congensis group',NULL,NULL,'medium','tolerant','medium',NULL,'Plants that are very vigorous and grow into moderately large trees. Yield ~1500-3000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sln-1-r','2026-06-03'),
 ('sln-2-r','Sln.2R','robusta','Guinea x Coffea congensis group',NULL,NULL,'medium',NULL,'large',NULL,'Plants that are very vigorous and grow into moderately large trees and produce large beans. Yield ~1500-3000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sln-2-r','2026-06-03'),
 ('sln-3-r','Sln.3R','robusta','Guinea x Coffea congensis group',NULL,NULL,'medium','tolerant','large',NULL,'Compact plant stature with good yielding potential, suitable for high-density planting. Yield ~1500-2500 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/sln-3-r','2026-06-03'),
 ('tr11','TR11','robusta','Congo group',NULL,NULL,'high','tolerant','medium',NULL,'Very high yield and quality. Strong growth. Yield ~5000-6000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/tr11','2026-06-03'),
 ('tr4','TR4','robusta','Congo group',NULL,NULL,'high','tolerant','medium',NULL,'High yield and wide adaptation to different environments. Yield ~5000-7000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/tr4','2026-06-03'),
 ('tr9','TR9','robusta','Congo group',NULL,NULL,'high','tolerant','large',NULL,'Very high yield and cup quality, large bean size. Yield ~5000-6000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/tr9','2026-06-03'),
 ('trs1','TRS1','robusta','Congo group',NULL,NULL,'high','tolerant','medium',NULL,'Wide adaptation to different environments; average input requirements. Yield ~4000-5000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/trs1','2026-06-03'),
 ('xanh-lun','Xanh lun','robusta','Congo group',NULL,NULL,'high','tolerant','large',NULL,'Compact, very high yield. High-quality, relative drought tolerance, late to ripen. Yield ~5000-6000 kg/ha.','World Coffee Research','https://varieties.worldcoffeeresearch.org/varieties/xanh-lun','2026-06-03');

-- ── Correct the 16 rows previously written from memory, now sourced from the PDF ──
UPDATE ref_varieties SET lineage='Introgressed (Catimor related)', optimal_alt_min_m=1000, optimal_alt_max_m=2000, yield_potential='high', rust_resistance='tolerant', bean_size='very large', flavor_potential='Good cup quality potential at high altitude.', notes='Very high yielding variety, with rust resistance and good quality at elevations above 1300 meters. Variety not uniform.', source_url='https://varieties.worldcoffeeresearch.org/varieties/anacafe-14', updated_at='2026-06-03' WHERE id='anacafe-14';
UPDATE ref_varieties SET lineage='Introgressed (Other)', optimal_alt_min_m=1300, optimal_alt_max_m=2000, yield_potential='high', rust_resistance='resistant', bean_size='small', flavor_potential='Very Good cup quality potential at high altitude.', notes='Recommended for specialty coffee production in Brazil. Broadly adaptable and drought-tolerant.', source_url='https://varieties.worldcoffeeresearch.org/varieties/catigua-mg2', updated_at='2026-06-03' WHERE id='catigua-mg2';
UPDATE ref_varieties SET lineage='F1 hybrid (introgressed)', optimal_alt_min_m=500, optimal_alt_max_m=2000, yield_potential='high', rust_resistance='resistant', bean_size='large', flavor_potential='Very Good cup quality potential at high altitude.', notes='Very high yielding with very good quality potential if planted in healthy soil and at elevations >1300 meters, with resistance to rust. Well-adapted for agroforestry.', source_url='https://varieties.worldcoffeeresearch.org/varieties/centroamericano', updated_at='2026-06-03' WHERE id='centroamericano';
UPDATE ref_varieties SET lineage='Introgressed (Catimor related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='high', rust_resistance='susceptible', bean_size='medium', flavor_potential='Low cup quality potential at high altitude.', notes='High yielding variety adapted to warmest zones and acidic soils.', source_url='https://varieties.worldcoffeeresearch.org/varieties/costa-rica-95', updated_at='2026-06-03' WHERE id='costa-rica-95';
UPDATE ref_varieties SET lineage='Introgressed (Sarchimor related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='medium', rust_resistance='tolerant', bean_size='medium', flavor_potential='Low cup quality potential at high altitude.', notes='High yielding plant adapted to medium altitudes. Resistant to coffee leaf rust and some nematodes.', source_url='https://varieties.worldcoffeeresearch.org/varieties/iapar-59', updated_at='2026-06-03' WHERE id='iapar-59';
UPDATE ref_varieties SET lineage='Ethiopian landrace', optimal_alt_min_m=1300, optimal_alt_max_m=2000, yield_potential='medium', rust_resistance='susceptible', bean_size='large', flavor_potential='Very Good cup quality potential at high altitude.', notes='High quality in Central America. Tolerant to major diseases, with low fertilizer requirement. Good choice for smallholder farmers.', source_url='https://varieties.worldcoffeeresearch.org/varieties/java', updated_at='2026-06-03' WHERE id='java';
UPDATE ref_varieties SET lineage='Bourbon-Typica group (Bourbon related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='medium', rust_resistance='susceptible', bean_size='large', flavor_potential='Good cup quality potential at high altitude.', notes='Tolerant to coffee berry disease. Found primarily in Kenya and Tanzania.', source_url='https://varieties.worldcoffeeresearch.org/varieties/k7', updated_at='2026-06-03' WHERE id='k7';
UPDATE ref_varieties SET lineage='Introgressed (Sarchimor related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='medium', rust_resistance='tolerant', bean_size='medium', flavor_potential='Good cup quality potential at high altitude.', notes='An elusive Puerto Rican variety.', source_url='https://varieties.worldcoffeeresearch.org/varieties/limani', updated_at='2026-06-03' WHERE id='limani';
UPDATE ref_varieties SET lineage='Bourbon-Typica group (Typica related)', optimal_alt_min_m=1300, optimal_alt_max_m=2000, yield_potential='medium', rust_resistance='susceptible', bean_size='large', flavor_potential='Exceptional cup quality potential at high altitude.', notes='Exceptional cup quality and drought tolerant, but highly susceptible to major diseases. Important variety for smallholder coffee growers in Rwanda and Burundi.', source_url='https://varieties.worldcoffeeresearch.org/varieties/mibirizi', updated_at='2026-06-03' WHERE id='mibirizi';
UPDATE ref_varieties SET lineage='F1 hybrid (introgressed)', optimal_alt_min_m=1000, optimal_alt_max_m=2000, yield_potential='high', rust_resistance='resistant', bean_size='large', flavor_potential='Very Good cup quality potential at high altitude.', notes='Very high-yielding variety, with rust resistance and good quality at elevations above 1300 meters. Variety not uniform.', source_url='https://varieties.worldcoffeeresearch.org/varieties/milenio', updated_at='2026-06-03' WHERE id='milenio';
UPDATE ref_varieties SET lineage='Introgressed (Sarchimor related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='high', rust_resistance='tolerant', bean_size='large', flavor_potential='Good cup quality potential at high altitude.', notes='A high yielding, rust-resistant Brazilian variety recently introduced to Costa Rica.', source_url='https://varieties.worldcoffeeresearch.org/varieties/obata-red', updated_at='2026-06-03' WHERE id='obata';
UPDATE ref_varieties SET lineage='Bourbon-Typica group (Typica related)', optimal_alt_min_m=1300, optimal_alt_max_m=2000, yield_potential='medium', rust_resistance='susceptible', bean_size='large', flavor_potential='Good cup quality potential at high altitude.', notes='A compact plant with medium yield and good quality, but highly susceptible to major diseases.', source_url='https://varieties.worldcoffeeresearch.org/varieties/pache', updated_at='2026-06-03' WHERE id='pache';
UPDATE ref_varieties SET lineage='Bourbon-Typica group (Typica related)', optimal_alt_min_m=1000, optimal_alt_max_m=2000, yield_potential='medium', rust_resistance='susceptible', bean_size='medium', flavor_potential='Good cup quality potential at high altitude.', notes='A good-yielding tall variety with drought and cold tolerance. Found mostly in Kenya and Uganda.', source_url='https://varieties.worldcoffeeresearch.org/varieties/sl14', updated_at='2026-06-03' WHERE id='sl14';
UPDATE ref_varieties SET lineage='F1 hybrid (introgressed)', optimal_alt_min_m=1000, optimal_alt_max_m=1400, yield_potential='high', rust_resistance='resistant', bean_size='large', flavor_potential='Very Good cup quality potential at high altitude.', notes='High yielding plant adapted to medium altitudes. Notably high acidity in the cup.', source_url='https://varieties.worldcoffeeresearch.org/varieties/starmaya', updated_at='2026-06-03' WHERE id='starmaya';
UPDATE ref_varieties SET lineage='Introgressed (Sarchimor related)', optimal_alt_min_m=500, optimal_alt_max_m=1400, yield_potential='medium', rust_resistance='tolerant', bean_size='large', flavor_potential='Good cup quality potential at high altitude.', notes='Well-adapted to medium altitudes. Variety not uniform.', source_url='https://varieties.worldcoffeeresearch.org/varieties/t5296', updated_at='2026-06-03' WHERE id='t5296';
UPDATE ref_varieties SET lineage='Bourbon-Typica group (Bourbon related)', optimal_alt_min_m=1300, optimal_alt_max_m=2000, yield_potential='medium', rust_resistance='susceptible', bean_size='medium', flavor_potential='Very Good cup quality potential at high altitude.', notes='A variety selected in El Salvador, and known for very good cup quality in the highest altitudes.', source_url='https://varieties.worldcoffeeresearch.org/varieties/tekisic', updated_at='2026-06-03' WHERE id='tekisic';

-- ── Group-level genealogy edges (parent group -> variety), OR IGNORE ──
INSERT OR IGNORE INTO ref_variety_lineage (parent_id,child_id,relation) VALUES
 ('ethiopian-landrace','ab3','selection'),
 ('bourbon','bourbon-mayaguez-139','selection'),
 ('bourbon','bourbon-mayaguez-71','selection'),
 ('typica','bpl10','selection'),
 ('typica','caripe','selection'),
 ('catimor','catimor-129','selection'),
 ('catimor','catisic','selection'),
 ('sarchimor','cuscatleco','selection'),
 ('catimor','fronton','selection'),
 ('typica','harar-rwanda','selection'),
 ('catimor','ihcafe-90','selection'),
 ('sarchimor','ipr-103','selection'),
 ('sarchimor','ipr-107','selection'),
 ('catimor','kartika-1','selection'),
 ('bourbon','kp423','selection'),
 ('catimor','lempira','selection'),
 ('sarchimor','monte-claro','selection'),
 ('typica','nyasaland','selection'),
 ('catimor','oro-azteca','selection'),
 ('sarchimor','paraiso','selection'),
 ('typica','pop3303','selection'),
 ('catimor','t5175','selection'),
 ('catimor','t8667','selection'),
 ('bourbon','venecia','selection');
